added documentation for installing and using VS Code Remote SSH. Updated
centerforaisafety/cluster-docs pull request #12
Opened 2023-06-27 21:39 UTC by rumiahkessel

Issue: https://github.com/centerforaisafety/cerberus-cluster/issues/81

The issue gives the actual information on the performance impacts of VS Code and ways to mitigate them if it becomes more of an issue in the future. For now it has minimal impact on server performance, so I created documentation explaining setup and install.

I also updated the table of contents as it was slightly out of date and added the windows related items to the gemfile.lock.

2023-06-28 18:10 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +1. Search extensions in VS Code for `ms-vscode-remote.remote-ssh` and install it
Add a period to each of these sentences.

2023-06-28 18:10 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +    1. [Using VS Code Remote SSH Extension](#using-vs-code-remote-ssh-extension)
I think we can rename this. Perhaps something similar to how we named the first entry under Specific Topics.

Something like: VSCode on the cluster

What do you think?

2023-06-28 18:15 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +1. Search extensions in VS Code for `ms-vscode-remote.remote-ssh` and install it
addressed

2023-06-28 18:15 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +    1. [Using VS Code Remote SSH Extension](#using-vs-code-remote-ssh-extension)
changed to VS Code on the Cluster

2023-06-28 18:26 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors such as vim and would prefer to develop as if you were on your local machine. We only ask tha
and/or instead of "...such as Vim and world prefer...".

2023-06-28 18:26 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors such as vim and would prefer to develop as if you were on your local machine. We only ask tha
We should emphasize that extensions may have a negative impact of VS Code performance and responsiveness.

2023-06-28 18:35 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors such as vim and would prefer to develop as if you were on your local machine. We only ask tha
addressed

2023-06-28 18:35 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors such as vim and would prefer to develop as if you were on your local machine. We only ask tha
changed to: `We suggest being mindful of how many extensions you install as too many can impact the responsiveness of your connection to the cluster.`

2023-06-28 21:50 UTC, steven-basart requested changes
Add an issue to update the Jupyter notebooks with VS Code so we can link the two

2023-06-28 21:50 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +
Remove this whitespace (tab) it's atrocious!

2023-06-28 21:50 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors and/or would prefer to develop as if you were on your local machine. We suggest being mindful
We don't need *all* of the context.

2023-06-28 21:50 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors and/or would prefer to develop as if you were on your local machine. We suggest being mindful
Give a banned list or approved list of sorts or exact number.

2023-06-28 21:52 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +You can now open folders and run commands on the terminal as if the server were your local machine. Repeat step 7 any time you want to connect to the server.
Explain RAM and CPU utilization to address some user concerns.

2023-06-29 01:36 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The remote SSH extension on VS Code is helpful if you are unfamiliar with using command line text editors and/or would prefer to develop as if you were on your local machine. We suggest being mindful
I Put 10 extensions as the limit. This is equivalent to a little over 2GB of memory usage in my experimentation (using the extensions from Zifan Wang).

2023-06-29 01:38 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +You can now open folders and run commands on the terminal as if the server were your local machine. Repeat step 7 any time you want to connect to the server.
Decided to rewrite the section to be less about installation instructions (gave links to the extension wikis instead), and instead speak more about our specific implementation and user concerns. Let me know what you think of this.

2023-07-05 20:16 UTC, steven-basart requested changes

2023-07-05 20:16 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The second option is the [Remote Tunnel extension](https://code.visualstudio.com/docs/remote/tunnels). This extension requires you to ssh into the server in a normal terminal window then run the serv
We strongly encourage to run the installation commands from your home directory on the server or local machine? Please be specific?

2023-07-05 20:16 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
Might be worth highlighting why we'd pick one over the other? I actually wasn't aware of the second one tbh.

2023-07-05 20:20 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
I originally had a sentence for that explaining that the tunnel is helpful if you want to use vscode with an interactive session on a compute node (instead of using jumps with ssh you just run the command while in the interactive session), but thought that might be too verbose. Can add it pretty easily to that last paragraph. Other than that they are essentially identical with our cluster

2023-07-05 20:22 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
We don't want to prioritize interactive sessions on the cluster (on compute nodes). So the setup seems more tedious?

2023-07-05 20:36 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +    1. [How to update gcc, g++, or glibc](#how-to-update-gcc-g-or-glibc)
Yep it works now

2023-07-05 20:49 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
Some users were finding it easier when they were also using jupyter notebooks.

2023-07-05 20:51 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The second option is the [Remote Tunnel extension](https://code.visualstudio.com/docs/remote/tunnels). This extension requires you to ssh into the server in a normal terminal window then run the serv
Yeah clarified this. I meant on the cluster in the /data directory

2023-07-05 20:56 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
I just added it since we had that user ask whether it was okay to use. It is about the same level of complexity to setup. I prefer Remote SSH, but they are pretty similar. The tunnels also lets you develop from a browser if you ever want that.

2023-07-05 23:42 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Both of these extensions deliver nearly identical development experiences and differ only in their connection method to the server.
Yeah good call jupyter notebooks are different workflow.  We can leave it in then.

2023-07-05 23:43 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +- [Table of Contents](#table-of-contents)
Remove this We don't need a link to table of contents

2023-07-05 23:46 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The second option is the [Remote Tunnel extension](https://code.visualstudio.com/docs/remote/tunnels). This extension requires you to ssh into the server in a normal terminal window then run the serv
under the correct privacy permissions. -> with the correct privacy permissions.

2023-07-06 00:25 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +- [Table of Contents](#table-of-contents)
fixed.

2023-07-06 00:25 UTC, rumiahkessel commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The second option is the [Remote Tunnel extension](https://code.visualstudio.com/docs/remote/tunnels). This extension requires you to ssh into the server in a normal terminal window then run the serv
fixed

2023-07-06 04:01 UTC, steven-basart approved these changes
LGTM

2023-07-06 16:32 UTC, merged