Updated nix user documentation to reflect the new way we want users t…
centerforaisafety/cluster-docs pull request #22
Opened 2024-03-05 21:00 UTC by andriy-safe-ai

…o use nix.

2024-03-06 23:18 UTC, steven-basart commented
Fix title so it can fit on one line

2024-03-06 23:23 UTC, steven-basart requested changes
Minor changes

2024-03-06 23:23 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Nix is a package manager for Linux, MacOS, Windows, and other Unix systems, with a wide selection of up-to-date packages. This document is a brief introduction to Nix and how to use it.
any modern operating system,

2024-03-06 23:23 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Use `nix-list`, an alias for `nix-env -q`, to list installed pacakges.
typo it's pak-ages

2024-03-06 23:23 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +Nix is a package manager for Linux, MacOS, Windows, and other Unix systems, with a wide selection of up-to-date packages. This document is a brief introduction to Nix and how to use it.
We should add a statement that support through Nix for us is experimental or something along those lines.  The fact that we're wiping out all of the users packages means it isn't stable and might even be deprecated in the future for something else.

2024-03-07 01:46 UTC, steven-basart approved these changes
LGTM

2024-03-07 18:23 UTC, andriy-safe-ai commented
Rebased to one commit. Merged.

2024-03-07 18:24 UTC, merged