Update documentation to include instructions for adding HF Models
centerforaisafety/cluster-docs pull request #25
Opened 2024-05-01 23:31 UTC by notrichardren

I just need confirmation that:
- The links work (e.g. to the Github folder)
- The chmod 777 + 775 is the best permissions (e.g. what if a model is broken? Would this make it difficult for them to re-download the model?)

2024-06-04 18:21 UTC, andriy-safe-ai requested changes

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/readme.md
In the documentation you refer to a file named `download_models.sh` but no such file exists. I think you're referring to `insert_public_models.sh`.

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/readme.md
I don't think that the scripts should be writeable. The users shouldn't be able to change the `cache_dir` directory either.

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/insert_public_models.sh
Have you considered passing the models are command line arguments?

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/insert_public_models.py
What tests have you performed for these scripts? Would you be able to add the tests and results to the PR please.

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/insert_public_models.sh
> +#SBATCH --partition=cais
Not all users have access to the `cais` partition. In this particular case, I think it would be best to not specify a partition. Slurm will then use the users default partition.

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/insert_public_models.sh
> +DRY_RUN=false
All global variables should be placed at the topic of the script. In general, we follow Googles shell style guide:  https://google.github.io/styleguide/shellguide.html

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/insert_public_models.sh
If you do decide on passing the models as cli arguments also add a `-h` and/or `--help` option to your script.

2024-06-04 18:21 UTC, andriy-safe-ai commented on add_public_hf_model/readme.md
> +for folder in */; do chmod 777 "$folder"; chmod -R 775 "$folder"*/; done
I think you might want to be more explicit as to what directory you want to run this in.

2024-07-10 03:59 UTC, notrichardren commented on add_public_hf_model/readme.md
How do I make the script not writable?

2024-07-10 03:59 UTC, notrichardren commented on add_public_hf_model/insert_public_models.sh
Agreed, this should be implemented

2024-07-10 04:00 UTC, notrichardren commented on add_public_hf_model/insert_public_models.py
See recording; it's a bit hard to do tests for these scripts. I ran it, and then it worked and the models were in /data/public_models. I can't really run it a second time because the folder itself I downloaded things into is not writable anymore.

2024-07-10 04:00 UTC, notrichardren commented on add_public_hf_model/insert_public_models.sh
> +#SBATCH --partition=cais
Agreed, this should be changed.

2024-07-10 04:01 UTC, notrichardren commented on add_public_hf_model/readme.md
> +for folder in */; do chmod 777 "$folder"; chmod -R 775 "$folder"*/; done
It says to run this command in the /data/public_models/huggingface directory

2024-10-18 17:04 UTC, andriy-safe-ai commented
Changes merged in different PR.

2024-10-18 17:04 UTC, closed without merging