Added documentation for shared Hugging Face cache..
centerforaisafety/cluster-docs pull request #30
Opened 2024-08-16 14:46 UTC by andriy-safe-ai

2024-08-16 15:31 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The global cache is updated regularly, with popular models added automatically based on usage patterns. Older or less frequently used models may be removed periodically to free up space. If you rely
This should give time frames and be less vague. 
Models unused for over 90 days may be removed at our discretion. Something like that.

2024-08-16 15:32 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +tokenizer = AutoTokenizer.from_pretrained(model_path)
Should maybe add an example for using a dataset in this same code

2024-08-16 15:33 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +  - Missing Dependencies: Ensure all required Python packages are installed. Use pip install transformers torch to install the basic dependencies.
Don't suggest `pip install` and just refer to the transformer installation page. Less likely for our docs to be out of date that way (unless the installation page changes).

2024-08-16 15:34 UTC, steven-basart requested changes
Some changes requested.

2024-08-16 15:34 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +  - Missing Token: Ensure you have an authentication token for models that require them. Consult the Hugging Face documentation for further information.
Again provide the link to the page.

2024-08-16 15:34 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +For additional help, reach out via the #shared-models-data Slack channel.
Why not help desk?

2024-08-16 15:34 UTC, steven-basart commented on _posts/2023-05-03-cais-cluster-documentation.md
> +  - Retention Policy: Models in the global cache may be removed if they are no longer frequently used. Important models can be flagged for retention by contacting the admins.
Again add time frames.

2024-08-17 17:55 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +The global cache is updated regularly, with popular models added automatically based on usage patterns. Older or less frequently used models may be removed periodically to free up space. If you rely
Updated.

2024-09-06 22:48 UTC, andriy-safe-ai commented on _posts/2023-05-03-cais-cluster-documentation.md
> +tokenizer = AutoTokenizer.from_pretrained(model_path)
We are no longer adding datasets to the cache.

2024-09-09 21:43 UTC, merged